site_name: JMusicBot ç¶­åŸº
site_description: "ğŸ¶ ä¸€å€‹ Discord éŸ³æ¨‚æ©Ÿå™¨äººï¼Œæ‚¨å¯ä»¥è¼•é¬†è¨­å®šå’Œé‹è¡Œï¼"
copyright: Copyright &copy; 2021 jagrosh
theme:
  icon: 
    logo: material/music-note
  favicon: assets/images/favicon.ico
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.indexes
  custom_dir: docs/overrides
  font:
    text: 'Fira Sans'
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: åˆ‡æ›åˆ°é»‘æš—æ¨¡å¼
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: åˆ‡æ›åˆ°ç™½äº®æ¨¡å¼
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AvianJay/MusicBot-zh_tw
    - icon: fontawesome/brands/discord
      link: https://discord.gg/0p9LSGoRLu6Pet0k
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX
repo_name: 'AvianJay/MusicBot-zh_tw'
repo_url: https://github.com/AvianJay/MusicBot-zh_tw
edit_uri: edit/gh-pages/docs/
site_url: https://avianjay.github.io/MusicBot-zh_tw
markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: "#"
nav:
  - index.md
  - Setup:
    - Setup Guide: setup.md
    - installing-java.md
    - getting-a-bot-token.md
    - finding-your-user-id.md
    - adding-your-bot.md
    - config.md
    - advanced-config.md
    - hosting.md
    - running-as-a-service.md
  - Reference:
    - commands.md
    - playlists.md
    - advanced-playlists.md
    - things-that-wont-be-added.md
    - advanced-eval.md
    - troubleshooting.md
